const Data = [
    {
        id: "1",
        title: "Beanies",
        category: "Beanies",
        price: "$20",
        img: "https://i.ibb.co/vdYg8SH/20230513-124615.jpg",
        desc: "A fitted beanie that is a light green color.",
    },
    {
        id: "2",
        title: "Slouchy Beanie",
        category: "Beanies",
        price: "$25",
        img: "",
        desc: "A neon green slouchy beanie.",
    },
    {
        id: "3",
        title: "Baby Blankets",
        category: "Blankets",
        price: "$25",
        img: "https://i.ibb.co/871Lvjz/20230513-125433.jpg",
        desc: "Various Baby Blankets of different patterns and colors.",
    },
    {
        id: "4",
        title: "Bandanas",
        category: "Bandanas",
        price: "$15",
        img: "https://i.ibb.co/F58tdh6/20230513-122946.jpg",
        desc: "Bandanas of different colors and designs. (100% Cotton)",
    },
    {
        id: "5",
        title: "Kid Bandanas",
        category: "Bandanas",
        price: "$12",
        img: "https://i.ibb.co/f1RK6pt/20230513-123040.jpg",
        desc: "A couple bandanas that are smaller, perfect for kids. (100% Cotton)",
    },
    {
        id: "6",
        title: "Baby Bibs",
        category: "Bibs",
        price: "$15",
        img: "https://i.ibb.co/DG96fgR/20230513-124814.jpg",
        desc: "Baby bibs of different colors. (100% Cotton)",
    },
    {
        id: "7",
        title: "Baby Bib + Matching Headband",
        category: "Bibs",
        price: "$18",
        img: "https://i.ibb.co/p1dx4Zd/20230513-124851.jpg",
        desc: "A bib with a matching headband. (100% Cotton)",
    },
    {
        id: "8",
        title: "Bracelets",
        category: "Bracelets",
        price: "$2",
        img: "https://i.ibb.co/2cNpLKT/20230513-124219.jpg",
        desc: "Bracelets of different sizes, designs and colors.",
    },
    {
        id: "9",
        title: "Monstera Coasters",
        category: "Coasters",
        price: "$15",
        img: "https://i.ibb.co/6rqxGCg/20230513-121925.jpg",
        desc: "A set of 4 coasters with a planter pot container. (100% Cotton)",
    },
    {
        id: "10",
        title: "Sunflower Coasters",
        category: "Coasters",
        price: "$15",
        img: "",
        desc: "A set of 4 coasters with a basket container. (100% Cotton)",
    },
    {
        id: "11",
        title: "Headbands",
        category: "Headbands",
        price: "$10",
        img: "https://i.ibb.co/pKM4qNB/20230513-123334.jpg",
        desc: "Various headbands with multiple colors. Adult and kid sizes. (100% Cotton)",
    },
    {
        id: "12",
        title: "Jar Openers",
        category: "Jar Openers",
        price: "$5",
        img: "https://i.ibb.co/xXHLv3h/20230513-123126.jpg",
        desc: "Rubber on the inside to grip onto jar lids for easier opening.",
    },
    {
        id: "13",
        title: "Keychains",
        category: "Keychains",
        price: "$3",
        img: "https://i.ibb.co/wBz1tk0/20230513-124414.jpg",
        desc: "Keychains of various colors and designs.",
    },
    {
        id: "14",
        title: "Dragonfly Keychains",
        category: "Keychains",
        price: "$3",
        img: "https://i.ibb.co/GFCsfk3/20230513-124005.jpg",
        desc: "Dragonfly keychains of various colors and sizes.",
    },
    {
        id: "15",
        title: "Hanging Organizers",
        category: "Organizers",
        price: "$15",
        img: "https://i.ibb.co/pwwTCVM/20230513-122324.jpg",
        desc: "A hanging pocket organizer for extra storage.",
    },
    {
        id: "16",
        title: "Pocket Organizers",
        category: "Organizers",
        price: "$25",
        img: "https://i.ibb.co/d5C80hS/20230513-122642.jpg",
        desc: "Goes under a couch cushion, seat cover or mattress to add extra storage.",
    },
    {
        id: "17",
        title: "Pet Bed",
        category: "Pet Bed",
        price: "$10",
        img: "https://i.ibb.co/WssWfYV/20230513-125516.jpg",
        desc: "A fluffy blanket that looks similar to grass, perfect for a pet to lay on.",
    },
    {
        id: "18",
        title: "Scrubbies",
        category: "Scrubbies",
        price: "$2",
        img: "https://i.ibb.co/qs9xLFC/20230513-122122.jpg",
        desc: "Can be used for dishes, a dishcloth, a washcloth, etc. (100% Cotton)",
    },
    {
        id: "19",
        title: "Scrunchies",
        category: "Scrunchies",
        price: "$1",
        img: "https://i.ibb.co/vctZgdw/20230513-124514.jpg",
        desc: "Are elastic so perfect for any hair.",
    },
    {
        id: "20",
        title: "Soap Savers",
        category: "Soap Savers",
        price: "$12",
        img: "https://i.ibb.co/6gsx9Ky/20230513-123223.jpg",
        desc: "Add a bar of soap and it's perfect for handwashing or even in the shower. (100% Cotton)",
    },
    {
        id: "21",
        title: "Towel Holders",
        category: "Towel Holders",
        price: "$8",
        img: "https://i.ibb.co/hZdGb5R/20230513-124650.jpg",
        desc: "Hang it off whereever and will hold a towel.",
    }
];

export default Data;